apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: microservicios
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  POSTGRES_INITDB_ARGS: "--auth-host=md5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: microservicios
data:
  init-databases.sql: |
    CREATE DATABASE db_publicaciones;
    CREATE DATABASE db_catalogo;
    CREATE DATABASE db_notificaciones;
    CREATE DATABASE db_auth;
    
    GRANT ALL PRIVILEGES ON DATABASE db_publicaciones TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE db_catalogo TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE db_notificaciones TO postgres;
    GRANT ALL PRIVILEGES ON DATABASE db_auth TO postgres;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: microservicios
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: postgres-init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgres-data
        emptyDir: {}
      - name: postgres-init-scripts
        configMap:
          name: postgres-init-scripts
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  namespace: microservicios
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP