server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # AUTH SERVICE
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<rest>.*), /api/auth/${rest}

        # PUBLICACIONES SERVICE
        - id: publicaciones-service
          uri: lb://SERVICIO-PUBLICACIONES
          predicates:
            - Path=/api/v1/publicaciones/**
          filters:
            - RewritePath=/api/v1/publicaciones/(?<rest>.*), /api/${rest}

        # NOTIFICACIONES SERVICE
        - id: notificaciones-service
          uri: lb://SERVICIO-NOTIFICACIONES
          predicates:
            - Path=/api/v1/notificaciones/**
          filters:
            - RewritePath=/api/v1/notificaciones(?<rest>.*), /api/notificaciones${rest}

        # CATÁLOGO SERVICE
        - id: catalogo-service
          uri: lb://SERVICIO-CATALOGO
          predicates:
            - Path=/api/v1/catalogo/**
          filters:
            - RewritePath=/api/v1/catalogo(?<rest>.*), /api/catalogo${rest}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: INFO
    org.springframework.cloud.loadbalancer: DEBUG